### ISSUE TITLE
Support for ROS2 Humble?

### ISSUE THREAD

**Issue by hnvakil** [Hokuyo-aut/urg_node2#3]
Hello!

Given ROS2 Galactic is no longer supported and ROS2 Foxy will lose support soon, are there any plans to add support for ROS2 Humble?

Thanks!

**Comment by hnvakil** [comment]
Update - I got the node working for ROS humble without issue (for anyone reading this in the future)

**Comment by UltraHertzz** [comment]
could you please share the node that works in humble? I have checked your repo but nothing related are found. In fact, in related package downloading period, the rosdep can not find the related package in namespace humble, could I manully change them to galactic and use the package that fits galactic in humble?

**Comment by huangda1982** [comment]
This node should work with humble. Could you tell me specifically what issue you encountered?

**Comment by UltraHertzz** [comment]
sry for late update. The code works on humble, the issue was IP configuration, which I have solved, thx for reply.
