### ISSUE TITLE
Message Filter dropping message: frame 'laser' at time ... for reason "Unknown"

### ISSUE THREAD

**Issue by FloBurger96** [Hokuyo-aut/urg_node2#9]
## Enviroment

- Ubuntu 20.0.4
- ROS2 Foxy
- Hokuyo URG-04LX-UG01

## Steps to reproduce

- Install urg_node2 in workspace
- run ros2 launch urg_node2 urg_node2.launch.py
- run rviz2

## Error

> 
> [INFO] [1699364574.126973952] [rviz]: Message Filter dropping message: frame 'laser' at time 1699364572.799 for reason 'Unknown'
> [INFO] [1699364574.223350880] [rviz]: Message Filter dropping message: frame 'laser' at time 1699364572.899 for reason 'Unknown'
> [INFO] [1699364574.351794720] [rviz]: Message Filter dropping message: frame 'laser' at time 1699364572.998 for reason 'Unknown'
> 

This goes on and no data is shown in rviz2. Ive already tried the "calibrate_time","synchronize_time" settings and also set the "time_offset" to different values around the difference of the timestamps.

I've also set up Ros2 on a different machine from scratch and get the same errors

**Comment by huangda1982** [comment]
Did you set the "Global Options" -> "Fixed Frame" in the "Displays" panel to "laser"?

![屏幕截图 2023-11-08 095523](https://github.com/Hokuyo-aut/urg_node2/assets/6382239/763bfb2e-288b-47e6-94e1-8f8a232ff36d)

**Comment by huangda1982** [comment]
Sorry, I only paid attention to "Message Filter dropping message" and didn't notice "frame 'laser'".

@f-wada , @j-fujimoto Any ideas about this?

**Comment by FloBurger96** [comment]
> Did you set the "Global Options" -> "Fixed Frame" in the "Displays" panel to "laser"?
> 
> ![屏幕截图 2023-11-08 095523](https://user-images.githubusercontent.com/6382239/281225839-763bfb2e-288b-47e6-94e1-8f8a232ff36d.png)

That worked. Thank you very much!
